#!/bin/bash

PY=./env/bin/python
FP=./manage.py
DOC=$(cat <<-END
    \n
    - COMMAND - [ ARGS ] -> REQUIRED\n
    \n
    - run ----- [ port ] -> false\n
    - migrate - [ make ] -> false\n
    - app ----- [ name ] -> true\n
    - test\n
    - user\n
    - reset\n
    - help\n
END
)

if [ $1 ]
    then
        if [ $1 == "run" ]
            then $PY $FP runserver $2
        elif [ $1 == "migrate" ]
            then $PY $FP makemigrations && $PY $FP migrate
        elif [ $1 == "user" ]
            then $PY $FP createsuperuser
        elif [ $1 == "app" ]
            then if [ $2 ]
                then $PY $FP startapp $2
            else echo "error: 'app' must have a name specified"
            fi
        elif [ $1 == "test" ]
            then $PY $FP test
        elif [ $1 == "help" ]
            then echo -e $DOC
        elif [ $1 == "reset" ]
            then rm ./db.sqlite3
        else 
            echo "error: chosen command '$1' not found"
        fi
else 
    echo "error: no command chosen. run 'manage help' for more info"
fi
